// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuu1LRyLjfIo2DMi-wrx22DZ1FS7k1Uj0',
    appId: '1:580954210493:web:1246ba92a5bd47ba29f7d4',
    messagingSenderId: '580954210493',
    projectId: 'hoainam-ebcb8',
    authDomain: 'hoainam-ebcb8.firebaseapp.com',
    databaseURL: 'https://hoainam-ebcb8-default-rtdb.firebaseio.com',
    storageBucket: 'hoainam-ebcb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzjDUa-DThB4qvSngYXC5nY3skaysp8ro',
    appId: '1:580954210493:android:af1a0682cfdafd4b29f7d4',
    messagingSenderId: '580954210493',
    projectId: 'hoainam-ebcb8',
    databaseURL: 'https://hoainam-ebcb8-default-rtdb.firebaseio.com',
    storageBucket: 'hoainam-ebcb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDag5BV4sbIwbRIEHxjd-xR3p-0ivoaHLY',
    appId: '1:580954210493:ios:ab12f75ca99bb0be29f7d4',
    messagingSenderId: '580954210493',
    projectId: 'hoainam-ebcb8',
    databaseURL: 'https://hoainam-ebcb8-default-rtdb.firebaseio.com',
    storageBucket: 'hoainam-ebcb8.firebasestorage.app',
    iosBundleId: 'com.example.datVeXemPhim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDag5BV4sbIwbRIEHxjd-xR3p-0ivoaHLY',
    appId: '1:580954210493:ios:ab12f75ca99bb0be29f7d4',
    messagingSenderId: '580954210493',
    projectId: 'hoainam-ebcb8',
    databaseURL: 'https://hoainam-ebcb8-default-rtdb.firebaseio.com',
    storageBucket: 'hoainam-ebcb8.firebasestorage.app',
    iosBundleId: 'com.example.datVeXemPhim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuu1LRyLjfIo2DMi-wrx22DZ1FS7k1Uj0',
    appId: '1:580954210493:web:022a4015383482ac29f7d4',
    messagingSenderId: '580954210493',
    projectId: 'hoainam-ebcb8',
    authDomain: 'hoainam-ebcb8.firebaseapp.com',
    databaseURL: 'https://hoainam-ebcb8-default-rtdb.firebaseio.com',
    storageBucket: 'hoainam-ebcb8.firebasestorage.app',
  );
}
